name: gdx_bigdata-infra

services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    hostname: minio
    container_name: gdx_bigdata_minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - gdx_bigdata
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DOMAIN: ${MINIO_URL}
      MINIO_COMPRESSION_ENABLE: "on"
      MINIO_BROWSER: "on"
      MINIO_BROWSER_REDIRECT: "false"
      MINIO_BROWSER_LOGIN_ANIMATION: "off"
    volumes:
      - ./data/minio/data/:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: gdx_bigdata_minio_init
    restart: on-failure
    networks:
      - gdx_bigdata
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for MinIO to be ready...';
        sleep 5;
        mc alias set bigdata-minio http://${MINIO_URL} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        echo 'Creating buckets...';

        mc mb --ignore-existing bigdata-minio/bigdata-dataset;
        mc mb --ignore-existing bigdata-minio/bigdata-spark-logs;
        mc mb --ignore-existing bigdata-minio/bigdata-ray-logs;
        
        echo 'Setting bucket policies...';
        mc anonymous set download bigdata-minio/bigdata-dataset;
        mc anonymous set download bigdata-minio/bigdata-spark-logs;
        mc anonymous set download bigdata-minio/bigdata-ray-logs;

        echo 'Buckets created successfully.';
      "

  prometheus:
    image: prom/prometheus:latest
    container_name: gdx_bigdata_prometheus
    restart: unless-stopped
    user: root
    networks:
      - gdx_bigdata
    ports:
      - "3001:9090"
    volumes:
      - "./assets/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./data/prometheus:/prometheus"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=5y"
      - "--web.enable-lifecycle"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:9090/-/healthy || exit 1"]
      interval: 3s
      retries: 20
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: gdx_bigdata_grafana
    restart: unless-stopped
    user: root
    networks:
      - gdx_bigdata
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:3000/api/health || exit 1"]
      interval: 3s
      retries: 20
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  gdx_bigdata:
    external: true