name: bigdata_master

services:
  spark-master:
    image: spark:4.0.1-scala2.13-java21-python3-ubuntu
    container_name: bigdata_spark_master
    hostname: spark-master
    restart: unless-stopped
    user: root
    networks:
      - bigdata
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_OPTS=-Dspark.dead.worker.persistence=2
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
    volumes:
      - ./assets/spark/conf/metrics.properties:/opt/spark/conf/metrics.properties
      - ./assets/spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./assets/spark/jars:/ext_jars:ro
      - ./data/spark/logs:/opt/spark/logs
      - ../../experiments:/opt/spark/work-dir
    ports:
      - "8080:8080"   
      - "7077:7077"  
      - "4040:4040"
    command: >
      bash -c "rm -rf /opt/spark/logs/* && cp /ext_jars/* /opt/spark/jars/ && /opt/spark/sbin/start-master.sh --properties-file /opt/spark/conf/metrics.properties --properties-file /opt/spark/conf/spark-defaults.conf && tail -f /dev/null"
    shm_size: '16gb'
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G

  spark-history-server:
    image: spark:4.0.1-scala2.13-java21-python3-ubuntu
    container_name: bigdata_spark_history_server
    hostname: spark-history-server
    restart: unless-stopped
    user: root
    networks:
      - bigdata
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_OPTS=-Dspark.dead.worker.persistence=2
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
    volumes:
      - ./assets/spark/conf/metrics.properties:/opt/spark/conf/metrics.properties
      - ./assets/spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./assets/spark/jars:/ext_jars:ro
      - ./data/spark_history_server/logs:/opt/spark/logs
      - ../../experiments:/opt/spark/work-dir
    ports:
      - "18080:18080"
    command: >
      bash -c "rm -rf /opt/spark/logs/* && cp /ext_jars/* /opt/spark/jars/ && /opt/spark/sbin/start-history-server.sh --properties-file /opt/spark/conf/metrics.properties --properties-file /opt/spark/conf/spark-defaults.conf && tail -f /dev/null"
    shm_size: '16gb'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  ray-head:
    image: rayproject/ray:2.51.1-py311-cpu
    container_name: bigdata_ray_head
    hostname: ray-head
    restart: unless-stopped
    user: root
    networks:
      - bigdata
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
    volumes:
      - ./data/ray/tmp:/ray_tmp
      - ../../experiments:/home/ray/experiments
    ports:
      - "8265:8265" 
      - "6379:6379" 
    command: >
      ray start --head --port=6379 --temp-dir /ray_tmp --dashboard-host 0.0.0.0 --node-ip-address ray-head --block 
    shm_size: '16gb'
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G

networks:
  bigdata:
    external: true